apiVersion: v1
kind: Service
metadata:
  name: itsm-frontend
spec:
  selector:
    app.kubernetes.io/name: itsm-frontend
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
