apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-collector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-collector
    spec:
      containers:
        - name: collector
          image: "{{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag }}"
          imagePullPolicy: {{ .Values.collector.image.pullPolicy }}
          env:
            - name: COLLECTOR_ENDPOINT
              value: "http://{{ .Release.Name }}-backend:{{ .Values.backend.service.port }}/api/v1/collect"
            - name: COLLECTOR_INTERVAL
              value: {{ .Values.collector.interval | quote }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secret
          resources:
            {{- toYaml .Values.collector.resources | nindent 12 }}
