apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  APP_ENV: {{ .Values.config.appEnv }}
  APP_PORT: {{ .Values.config.appPort | quote }}
  APP_LOG_LEVEL: {{ .Values.config.logLevel }}
  DB_TYPE: {{ .Values.config.dbType }}
  DB_HOST: {{ .Values.config.dbHost }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName }}
